### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by bach5000**
Resolves issue #2.
This has been tested on x86_64 and it works 🎊 
Update: Tested on x86_gcc2 and it also works!

### CODE REVIEW

**Comment by owenca** [comment]
Nice try, but this is not the right way to fix it. :)

The problem with AboutWindow.cpp is that it's out of sync with its header AboutWindow.h. Just copy the latest .cpp file into the interface folder and all the compiler error messages will be gone.

As to DefaultTypes.h, g++ gives misleading diagnostic messages. (clang is known to give better error messages, but I didn't try it here.) The problem is [here](https://github.com/HaikuArchives/ResourceEdit/blob/master/source/DefaultTypes.h#L33). Remove the `~` and voila, the application builds without a hitch.

**Comment by scottmc** [comment]
Once you get it working, perhaps do #1.  Then open enhancement tickets for possible new features.  Adding these new features may be a future task.

**Comment by bach5000** [comment]
@owenca About the AboutWindow.cpp :)
Do we really need to copy it into the interface folder when we could simply use Haiku's AboutWindow.h?
I agree with removing the `~` from `~0`. I actually tried this, but I was afraid that the `~0` was placed there for a purpose... I'm still not sure.

**Comment by owenca** [comment]
> @owenca About the AboutWindow.cpp :)
> Do we really need to copy it into the interface folder when we could simply use Haiku's AboutWindow.h?

`#include`ing a header will only allow you to compile (but not necessarily link) the code. It just happens that ResourceEdit doesn't (yet) use anything from `AboutWindow.h`, so removing `AboutWindow.cpp` from `Makefile` will still allow it to be built successfully. (This also means that you can remove the `#include` line from `ResourceEdit.cpp`.)

I think the AboutWindow is intended for the Help menu, which is empty right now. I'd keep the latest `AboutWindow.cpp` in the repo for now.

> I agree with removing the `~` from `~0` could fix the build. I actually tried this, but I was afraid that the `~0` was placed there for a purpose... I'm still not sure.

It looks like an obvious typo to me from its intended use (the `uint32 size` field of `ResourceType`).

I suggest that for this "Fix build" PR, you only fix what's necessary to make ResourceEdit build and start. Then you can create a separate PR for fixing bugs in, and add features to, the application.

**Comment by bach5000** [comment]
@owenca 
> I suggest that for this "Fix build" PR, you only fix what's necessary to make ResourceEdit build and start. Then you can create a separate PR for fixing bugs in, and add features to, the application.

That's a good idea. I might have to start doing that.

As for the AboutWindow, I'll re-add the newest version back to the repo.
For the `~0`, you made a pretty good point. I already changed it to 0 so that should be taken care of :)

**Comment by bach5000** [comment]
@scottmc Added issues!
Seems like the author has seen QuickRes before... the author proposed some similar features from QuickRes in the source code  :)

**Comment by scottmc** [comment]
Is this ready for merge yet?

**Comment by bach5000** [comment]
@scottmc It think it should be ready.

**Pull request merged**
